### ISSUE TITLE
Manifest merger issue

### ISSUE THREAD

**Issue by pietrini** [TagCommander/Android#1]
Lib version: 4.1.0

Documents/rts/srg/srg-player-android/SRG-Player/src/debug/AndroidManifest.xml:16:9-49 Error:
    Attribute application@label value=(@string/APP_NAME_VARIANT) from AndroidManifest.xml:16:9-49
    is also present at [com.tagcommander.lib:core:4.1.0] AndroidManifest.xml:13:9-41 value=(@string/app_name).
    Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:12:5-143:19 to override.

Documents/rts/srg/srg-player-android/SRG-Player/src/debug/AndroidManifest.xml:20:9-36 Error:
    Attribute application@supportsRtl value=(false) from AndroidManifest.xml:20:9-36
    is also present at [com.tagcommander.lib:core:4.1.0] AndroidManifest.xml:14:9-35 value=(true).
    Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:12:5-143:19 to override.

The core library of tag commander seems to have an manifest who contains an application with a label and also define a rtl spec.
This creates an issue with the manifest merger and those parameters are not required for a lib.

**Comment by CommandersAct** [comment]
I'll check, come back at you as soon as possible.

**Comment by CommandersAct** [comment]
Updated, waiting for Bintray to validate the releases.
