### ISSUE TITLE
Add Privacy module to jcenter

### ISSUE THREAD

**Issue by therealmyluckyday** [TagCommander/Android#10]
The Privacy module is not included jcenter: https://jcenter.bintray.com/com/tagcommander/lib/

Which means we have to manually manage this dependency! Please add it.

**Comment by CommandersAct** [comment]
Hello !

The request is sent, meanwhile you can also use :

allprojects {
    repositories {
(...)
        maven {
            url  "https://dl.bintray.com/tagcommander/maven"
        }
    }
}
