### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by dcampogiani** [TagCommander/Android#12]
Source: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by afaucogney** [comment]
Any news about this one month later ?

**Comment by CommandersAct** [comment]
Nothing for now, we sadly have more pressing matters

**Comment by CommandersAct** [comment]
Hello ! 
Our latest releases are now available on Maven Central starting with:
Core : 4.6.0
SDK : 4.5.0
Privacy : 4.7.3
Partners : 4.4.5

We should migrate part of the old releases later on. But we can't give any date for that now.
Beware that the IAB module is not available on MavenCentral for now as it would take more work to do so and it will need to be added manually for now.
