### ISSUE TITLE
Location permission

### ISSUE THREAD

**Issue by SebastienChauvin** [TagCommander/Android#2]
Are there plans to release a version without the location permission? I do not believe requiring user geographical position is desired in our use case.

**Comment by SebastienChauvin** [comment]
Just to reiterate on this issue. The TagCommander library are used in multiple products. Some products like weather apps do require location and will have the location permission in their manifest, some like the video player do not. We need the following from the TagCommander sdk:

- No permission requirement in the library AndroidManifest.xml. We do not want any location permission visible for older devices (pre 6.0)

The permission requirement for Coarse and or precise location will be added by the application manifest

**Comment by CommandersAct** [comment]
Hello !
I'm really sorry I thought I activated the "send email" option for issues. Sadly, it was not the case, especially since the answer is so simple.

You don't have to request for location permission, the documentation is unclear, I need to make it more explicit.
Simply don't call "TCLocation.getInstance(context);" and it will never be initialised, and you'll never need to ask for location permission to your users.

If you ever need it, check that the permission was granted before calling "TCLocation.getInstance(context);".

**Comment by SebastienChauvin** [comment]
What you say is correct for devices in 6.0 and above. For devices pre 6.0, we still have the issue that the AndroidManifest of the library includes the location permissions and adds them by default to our own application. 
We currently use the folllowing to work around this issue, but this causes other trouble for other users:
`    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        tools:node="remove" />
`

We understand the TCLocation.getInstance is not required, but we need a version of the library without permission in its AndroidManifest as well.

We believe it would be more appropriate to have the application add those permission in their own AndroidManifest rather than pushing them from the library.

**Comment by CommandersAct** [comment]
Indeed!

I removed the permissions from the Manifest.

**Comment by SebastienChauvin** [comment]
Cool thanks. Let us know when you have a release with this

**Comment by pietrini** [comment]
Is it fixed ?

**Comment by CommandersAct** [comment]
Yes it has been released 7 days ago. Are you still having issues?

**Comment by pietrini** [comment]
No it's fine now, you can close this issue
