### ISSUE TITLE
Error:Failed to resolve: com.tagcommander.lib:SDK:4.1.2

### ISSUE THREAD

**Issue by guntherhoppe** [TagCommander/Android#4]
Regarding to your jcenter setup:
It seems the SDK version 4.1.2 is not available on default jcenter. I always get an error saying: Error:Failed to resolve: com.tagcommander.lib:SDK:4.1.2

If I try to manually download it from here: https://dl.bintray.com/tagcommander/maven/com/tagcommander/lib/SDK/4.1.2/,
I have to to enter a valid user / password.

With:
https://dl.bintray.com/tagcommander/maven/com/tagcommander/lib/SDK/4.1.1/,
it works without user / password.

**Comment by CommandersAct** [comment]
This is quite strange. I didn't change anything in bintray configuration.

You can download it [there](https://github.com/TagCommander/Android/tree/master/TCSDK) meanwhile, I'll look into it

**Comment by CommandersAct** [comment]
It seems that the artefacts were not considered as published.
It should be working now.

**Comment by guntherhoppe** [comment]
Yes - works now again. Thx.
