### ISSUE TITLE
Tags are by default displayed on the console

### ISSUE THREAD

**Issue by Didier116** [TagCommander/Android#6]
Hello,

I think I found a security issue.

Indeed , by default tags are visible on the LogCat console even on Release (debuggable false), which can be considered a security breach.

The documentation provides to not display them using _Log.NONE_ constant but this constant doesn't existe.

Moreover, even considering that the variable existe and equals "0", the following comparison couldn't work (TCLogger.java:63 _logMessage(...)_) : 
` if (level >= stateLevel)
  { 
       logToConsole(message, level); 
   }`

The only workaround I use is setting debug level at 8 :
`TCDebug.setDebugLevel(android.util.Log.ASSERT + 1);`

**Comment by CommandersAct** [comment]
Hello !
Created a new version 4.1.8 of the core module with a default loglevel which logs nothing. It's indeed way better like this :)

Don't understand where this Log.NONE comes from though (I put it in the documentation). I've been using Java's Log level, which doesn't have NONE.

**Comment by Didier116** [comment]
Thank you for this responsiveness.

It's better, Log are disable on Release, but they are still displayed even when TCDebug.setDebugLevel is not called.

Maybe an issue with others components ?
```
compile 'com.tagcommander.lib:core:4.1.8'
compile 'com.tagcommander.lib:SDK:4.1.5'
compile 'com.tagcommander.lib:segment:4.1.1'
```

**Comment by CommandersAct** [comment]
Their should be no differences between release or debug in this case. Are you sure it's not called anywhere? I can't see logs in any part of the SDK on my test app with this library setup.

**Comment by Didier116** [comment]
My bad,

It was some olds manuals logs.

Thank you again for your help and your responsiveness !
