### ISSUE TITLE
Failed to resolve: com.tagcommander.lib:core:4.1.8

### ISSUE THREAD

**Issue by sabrinaj** [TagCommander/Android#7]
Hello,

I have some issues using the last version of core and SDK. It seems that the [link is empty](https://dl.bintray.com/tagcommander/maven/com/tagcommander/lib/core/4.1.8/)
`Failed to resolve: com.tagcommander.lib:core:4.1.8`
`Failed to resolve: com.tagcommander.lib:SDK:4.1.5`

**Comment by CommandersAct** [comment]
Sorry I forgot to press the publish button 👎 
This should be ok now

**Comment by sabrinaj** [comment]
It's OK for the core but still KO for the SDK

**Comment by CommandersAct** [comment]
Done. Didn't realised it overrided the SDK.

**Comment by sabrinaj** [comment]
OK for both now, thank you for your quick response.

**Comment by CommandersAct** [comment]
Sorry for missing it
